### ISSUE TITLE
Toggle on-off does not work properly

### ISSUE THREAD

**Issue by alexandercutler** [PhysicalAddons/physical-starlight-and-atmosphere#14]
**Describe the bug**
When toggling "off" the "Physical Atmosphere" function in the properties panel, two things are not correctly switched off:

1) A "Sun" light is left - which can be easily deleted
2) The "world light" is dark - and for the life of me I cannot work out how to "lighten" it up - all the settings  appear back to default, but it is like it is not only dark, but in some form of pea soup fog (although no sign of fog) - what do I mean? Well an emitting material's light will travel only an incredibly short distance.

**General information**
- Blender version: 2.83 LTS
- Engine: Cycles & Eevee
- Operating System: Windows 10 
- Other info that could be useful: 2x Intel i9, 2x NViDIA RTX 2080 Super

**To Reproduce**
Open new blank project, switch into cycles view.  Look at the scene of the cube - you can see the cube.  
Go to properties and toggle on Physical Atmosphere
All ok still.
Then toggle off Physical Atmosphere
Oh - - it's all gone dark - what's wrong? And there is a Sun light left over.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Comment by karlisup** [comment]
Hi @alexandercutler,
Thank you for your patience! Part of this regarding darkness (exposure issues #8, #11) was fixed in PSA v1.2.2 bugfix. Regarding the sun which was left if the scene we had a discussion with @martinsh and at first it was considered a feature, but as time goes by we see that it causes more issues than it helps so fixing issue #1 will solve this.

Currently, I will close this issue as one of the issues is already reported (please, follow issue #1 for the progress) and exposure-related issues are already closed.
