### ISSUE TITLE
Emission materials neutered by Physical Atmosphere add-on

### ISSUE THREAD

**Issue by alexandercutler** [PhysicalAddons/physical-starlight-and-atmosphere#15]
Any Emission material, after the add-on is switch on, stops glowing completely- it does however, continue to emit some light, but only a tiny fraction of what was emitted before.

More problematic, is that if you then switch off Physical Atmosphere, the emissions do NOT go back to normal.  To demonstrate I have taken three simple images,
[Replace this with a clear and concise description of what the issue is about.]

**General information**
- Blender version: 2.83 LTS
- Engine: Cycles
- Operating System: Windows 10
- Other info that could be useful: NVDIA RTX 2080 Super 

**To Reproduce**
1. Create a simple project with an emitting material.
2. Render in cycles. [see first screenshot]
3. Switch on Physical Atmosphere
4. Re-Render in cycles - not the emitting material no longer glows, and the light emitted is now fraction of what was before [see second screenshot]
5. Switch off Physical Atmosphere
6. Re-Render in cycles [see third screenshot]
7. Note the problem is now even worse - the Physical Atmosphere module has clearly NOT restored settings correctly

Problem only happens in Render - not when using Cycles in Viewport.   I have checked through all the visible settings and can find no reason for this behaviour.

**Screenshots**
![Emission pre Physical Atmosphere](https://user-images.githubusercontent.com/66945863/84743218-8a216680-afa9-11ea-8463-839d13c5d7c8.png)
![Emission with Physical Atmosphere](https://user-images.githubusercontent.com/66945863/84743234-90174780-afa9-11ea-83c7-6c5479b5873e.png)
![Emission with Physical Atmosphere disabled](https://user-images.githubusercontent.com/66945863/84743243-93aace80-afa9-11ea-8036-09a466d215f9.png)

**Comment by karlisup** [comment]
Hi @alexandercutler,
Thank you for your patience! I did try to reproduce the issue, but I didn't manage to do so. I suspect that this issue has also been related to a feature we implemented which caused to exposure change and act in weird ways.

We did implement a fix on the 16th of July and this should be fixed in PSA addon v1.2.2. Are you still currently working with emission material? Could you, please confirm that this issue is fixed? Here are my three demo renders of a surface set to `emission`. 
![1st-render](https://user-images.githubusercontent.com/3999661/89908146-38d2d380-dbf6-11ea-8fc5-289a92a9127e.png)
![2nd-render](https://user-images.githubusercontent.com/3999661/89908152-3a040080-dbf6-11ea-96eb-e95c55298452.png)
![3rd-render](https://user-images.githubusercontent.com/3999661/89908159-3c665a80-dbf6-11ea-8830-5118e270989f.png)

**Comment by karlisup** [comment]
I'll currently close the issue as inactive, but if you manage to reproduce the issue, just drop the line and I'll get back to you.
