### ISSUE TITLE
Sky texture disappear

### ISSUE THREAD

**Issue by ArrigoniAlex** [PhysicalAddons/physical-starlight-and-atmosphere#25]
I am using starlight to iluminate a scene, i don't know why, but the atmosphere texture disapeared and won't comeback, even if I turn off/on the atmosphere or the addon. It happened twice now. The only work around i figured is to start a new blender scene and remake the sky and bringing my geometry to the new scene. How can I fix?

- Blender version:  2.8.3.0
- Engine: Cycles
- Operating System: Windows 10
- Intel i7, 48 RAM, gtx 1050

I don't know how to reproduce the error. Don't know why this is happenning.

Screenshots

![image](https://user-images.githubusercontent.com/22716690/89709284-e0c97200-d954-11ea-84fe-4de9a88eefc8.png)

**Comment by karlisup** [comment]
Hi @ArrigoniAlex,
Was playing with the settings I saw in the screenshot to try and reproduce the issue. Currently, it seems that the atmosphere settings `sun intensity` set to 20M and `atmosphere intensity` set to 200 are super bright. But then again this super bright atmosphere is cut off by the Clamping (setting maximum direct light to 0.01) which results in what you see.
I wonder what happens if you play with these values:
1. `Render Properties > Light Paths > Direct Light`
2. `PSA addon > Sun Intensity`
3. `PSA addon > Atmosphere Intensity`

Does sky texture reappear to you? 
Here is my reproduced result:
![image](https://user-images.githubusercontent.com/3999661/89772801-5414e480-db0b-11ea-9f00-61b301d289f7.png)

**Comment by ArrigoniAlex** [comment]
Hi Karl!
Thanks for the response.
Actually it didn't reappear. I created another file, putted on the settings I was using before and copy/pasted my geometry in the new file. After a while a lost the sky texture again and had to do the work around again. Sun and atmosphere intensity are the default values for when I turn starlight on. The clamp was for trying to deal with some fireflies in the render.

**Comment by karlisup** [comment]
Could you please check the version of the addon under addon preferences? Are you using the latest one 1.2.2? I am wondering if this is not one of the exposure issues again.
![image](https://user-images.githubusercontent.com/3999661/89776233-22ebe280-db12-11ea-8f50-616eaa629bcd.png)

**Comment by ArrigoniAlex** [comment]
1.2 

![image](https://user-images.githubusercontent.com/22716690/89776650-b3a9ca80-dae0-11ea-9fa9-438cc34cf6a7.png)

**Comment by karlisup** [comment]
Grab the latest version at the virtual store you bought your copy:
https://gumroad.com/ or https://blendermarket.com/

**Comment by ArrigoniAlex** [comment]
Thx!

**Comment by karlisup** [comment]
Thank you for your time opening the ticket!
