### ISSUE TITLE
Can't use the Addon on more than one Scene

### ISSUE THREAD

**Issue by karlisup** [PhysicalAddons/physical-starlight-and-atmosphere#26]
**Describe the bug**

A Background scene for only the atmosphere and a Foreground scene with objects that need to have a transparent background but receive the light from the addon.

When the addon gets enabled on the Background scene and then on the Foreground scene with transparency checked in the Film tab the Addon node disappears from the Background scene.

I now have to use a workaround with a holdout plane to eliminate the atmosphere to come through on some layers and have to use the Add blend mode instead of alpha over to merge the layers. Still not ideal.

_Possible workaround (?):_
I copy and pasted the Atmospheric node from one scene to another and didn't touch the button to enable/disable the addon. It now works as expected.

_Description copied and a bit adapted from [this issue](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/16)._

When new Scene created such error in console is returned:
![image](https://user-images.githubusercontent.com/3999661/89885745-319ace00-dbd4-11ea-837b-1372fd450b90.png)

**General information**
- Blender version: reproduced on 2.83.2 and 2.83.4
- Addon version: 1.2.2
- Engine: Evee and Cycles
- Operating System: Windows 10

**To Reproduce**
1. Open a new project
2. Enable PSA addon
3. In topbar (or any other possible way) create a new scene

**Screenshots**
![image](https://user-images.githubusercontent.com/3999661/89886128-c998b780-dbd4-11ea-8df8-17a95f4e183d.png)

**Comment by karlisup** [comment]
Hi! If somebody is using Scenes in Blender and can explain to me **how would you expect this addon to work with scenes** I would appreciate that. Also, I don't know how commonly people use this feature and would appreciate it if you could **upvote the issue**. It would help me prioritize feature development better.

**Comment by LennartSolik** [comment]
Well my problem and the reason i reported the issue was that i needed the athmosphere in 2 scenes (one with only the athmosphere and one with the model and tranparent background but still lit by the athmosphere addon) and that the toggle on/off button removed the node in the world editor from the "not active scene". So it was just possible to have one active athmosphere in your whole Blender project.

To fix the removal of the node in the "not active scene" i set the athmosphere to desired liking and then copied the node in the world shader editor to the other scenes world shader editor and never touched the on/off toggle again. After this i was able to control, for example the time of day and it would update on the second scene also.

It could be also really cool to have 2 scenes with 2 different athmospheres. As it is now its possible to control both nodes from one scene but enabling/disabling the addon removes one node from the world shader editor from the not active scene.

Maybe a toggle button to "link" settings from one scene to the athmosphere world node from another scene. And a toggle to "unlink" the settings so you can control 2 or even more different athmospheres in additional scenes.

**Comment by ZanQdo** [comment]
I would propose to move the properties storage to the World datablock instead of the Scene datablock. This way just by linking or copying the world, you get all the Physical Sky properties.

The addon's UI is even already inside the world window but the actual properties are under the scene. This could be changed for consistency and easy of use between different scenes.

![image](https://user-images.githubusercontent.com/999476/107079256-315f4200-67b5-11eb-87a9-ca1f46727ef1.png)

**Comment by karlisup** [comment]
This bug was fixed in v1.4 early stage in a way we thought was right. With a help of @ZanQdo it was clear that it wasn't the right way to go and this has to be redone. Variables must be stored in a World data block instead of the scene and that would solve also issues with working with the scenes. As scenes are not causing any more console errors I would like to close this issue, just for the sake of keeping the bug tracker clean.
