### ISSUE TITLE
MacOS install

### ISSUE THREAD

**Issue by Ingapambi** [PhysicalAddons/physical-starlight-and-atmosphere#30]
1.3 installs fine but doesn't enable.

Imac Pro OS 11.01.
<img width="2560" alt="Screen Shot 2020-12-13 at 9 48 11 AM" src="https://user-images.githubusercontent.com/44510383/102019502-ce0ee180-3d28-11eb-8516-286e203f9334.png">

**Comment by karlisup** [comment]
Hi @Ingapambi,
Did update from the previous version or It's a first-time install on this iMac Pro? This looks like an error I've seen before which was caused by installing a new version on top of the old one. If it is the case and this is not first-time install. Try deleting the addon, and reinstalling it as it's described in the [updating](https://www.physicaladdons.com/psa/updating/) section. Let me know if this did work for you.

**Comment by Ingapambi** [comment]
All is right with the world because it worked. Thankyou  for your prompt help.🙂

John Ross

**Comment by karlisup** [comment]
I am glad that it helped ;).
