### ISSUE TITLE
Atmosphere Looks Different after File Save -> Load

### ISSUE THREAD

**Issue by hnoerenberg** [PhysicalAddons/physical-starlight-and-atmosphere#60]
**Describe the bug**
I constantly have the problem that PSA gives a different result after loading a file. I attached two screenshots. Tested this with B3 but I had exactly the same problem with 2.93.

**General information**
- Blender version: 3.0.0 + 2.93.7
- Addon version: 1.4.x - 1.4.4
- Engine: Eevee & Cycles
- Operating System: Win + Linux (Files should be interoperable)
- Other info that could be useful: [e.g. CPU, GPU, etc.]: GPU or CPU makes no difference

**To Reproduce**
You can easily reproduce the issue by creating a new file and then save the file. Hit render -> Make a screenshot -> Reload Blender with the saved file -> Render.
You get a different result.

**Screenshots**
Before Reload:
![PSA_Before_Save](https://user-images.githubusercontent.com/55043719/149651478-14cd04e5-bd2e-49ef-8faa-0d42e87ba578.jpg)
After reload:
![PSA_After_Save](https://user-images.githubusercontent.com/55043719/149651483-5c303a2a-4770-4092-beea-a3b734d8bbc7.jpg)

It feels very weird that the color on the sidepanel for inscattering is changing etc. Maybe there are some Statics overriding the files saved state.

Addition: Is there still an uncompatibility with Sun Position Addon?

**Comment by karlisup** [comment]
Hi @hnoerenberg,
Sorry for not giving even a quick response regarding this issue. During this time together with the team, we were trying to push the PSA v1.5 release which did address a lot of issues. Now, this should have been fixed as this issue was related to custom preset functionality implementation. If this issue still persists (it should not), feel free to reopen the ticket.

_Best Regards,
Karlis_
